# Generated by Django 3.1.3 on 2020-11-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0003_auto_20201115_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='bookmark',
        ),
    ]
