# Generated by Django 3.1.3 on 2020-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_articles', '0007_auto_20201115_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='articles',
            field=models.ManyToManyField(related_name='bookmark', to='news_articles.NewsArticle'),
        ),
    ]
