# Generated by Django 3.1.3 on 2020-11-15 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_articles', '0008_auto_20201115_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
