# Generated by Django 3.1.3 on 2020-11-16 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_articles', '0009_auto_20201115_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(choices=[('politics', 'Politics'), ('health', 'Health'), ('education', 'Education')], max_length=15),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
