# Generated by Django 3.1.3 on 2020-11-16 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_articles', '0010_auto_20201116_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('health', 'Health'), ('education', 'Education')], max_length=15),
        ),
    ]
