# Generated by Django 3.1.3 on 2020-11-17 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_articles', '0011_auto_20201116_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
